"""Partition only the existing 768 KiB other-closeout allowance."""
FILE_CAPS={"HELPER_SETUP.json":65536,"HELPER_TERMINAL.json":65536,
           "HELPER_ADMISSION.json":8192,"HELPER_OUTER_STATUS.json":32768}
TOTAL_RESERVED=sum(FILE_CAPS.values())
OTHER_ORIGINAL=3*1024**2//4
OTHER_REMAINDER=OTHER_ORIGINAL-TOTAL_RESERVED
