"""Supplied rational/dyadic descent witnesses only; no production generator or search."""

import json
import math
import sys
from fractions import Fraction as F

PAIRS = ((2, 0), (3, 1), (6, 4), (7, 5), (10, 8), (11, 9))
ZERO, E1, E2 = (F(0), F(0)), (F(1), F(0)), (F(0), F(1))
STEP, NET, PATH = F(1, 20), F(1, 5), F(2, 5)
GRID = 2**80


def dot(a, b):
    return sum((x * y for x, y in zip(a, b, strict=True)), F(0))


def add(a, b):
    return tuple(x + y for x, y in zip(a, b, strict=True))


def scale(a, x):
    return tuple(x * y for y in a)


def fixture(a=E1, rhs=F(1, 10)):
    A, b, c = [ZERO] * 12, [F(-1)] * 12, [F(0)] * 6
    A[2] = A[0] = a
    b[2] = b[0] = rhs
    return A, b, c


def quantities(A, b, c, r):
    assert len(A) == len(b) == 12 and len(c) == 6
    D = [scale(add(A[i], scale(A[j], -1)), F(1, 2)) for i, j in PAIRS]
    deficits = [max(F(0), bi - dot(ai, r)) for ai, bi in zip(A, b, strict=True)]
    drift = [ci + dot(di, r) for ci, di in zip(c, D, strict=True)]
    components = {
        "proximal": dot(r, r) / 2,
        "deficit": dot(deficits, deficits) / 24,
        "drift": dot(drift, drift) / 48,
    }
    gradient = tuple(
        r[j]
        - sum((ai[j] * z for ai, z in zip(A, deficits, strict=True)), F(0)) / 12
        + sum((di[j] * z for di, z in zip(D, drift, strict=True)), F(0)) / 24
        for j in range(2)
    )
    M = 1 + sum((dot(ai, ai) for ai in A), F(0)) / 12
    M += sum((dot(di, di) for di in D), F(0)) / 24
    return components, gradient, M


def norm_upper(square):
    k = math.isqrt(square.numerator * GRID * GRID // square.denominator)
    if k * k * square.denominator < square.numerator * GRID * GRID:
        k += 1
    upper = F(k, GRID)
    assert upper * upper >= square
    return upper


def certificate(A, b, c, w, length, r):
    assert 0 <= length <= PATH and dot(w, w) <= NET * NET
    assert dot(w, w) <= length * length
    rho = min(STEP, PATH - length)
    initial, g0, M = quantities(A, b, c, ZERO)
    final, gradient, _ = quantities(A, b, c, r)
    j0, jr = sum(initial.values(), F(0)), sum(final.values(), F(0))
    s, gain = -dot(g0, r), j0 - jr
    eta = F(1, 2**30) * max(F(1), j0)
    step2, net2 = dot(r, r), dot(add(w, r), add(w, r))
    charged = length + norm_upper(step2)
    geometry = step2 <= rho * rho and net2 <= NET * NET and charged <= PATH
    excess = gain - s / 4 - eta
    return {
        "input": {
            "A": [tuple(row) for row in A],
            "b": list(b),
            "c": list(c),
            "w": tuple(w),
            "path_upper": length,
        },
        "actual_r": r,
        "M_exact": M,
        "g0": g0,
        "gradient_at_actual_r": gradient,
        "J0": j0,
        "J_actual": jr,
        "weighted_components_before": initial,
        "weighted_components_after": final,
        "component_decreases": {key: initial[key] - final[key] for key in initial},
        "s": s,
        "gain": gain,
        "eta": eta,
        "strict_acceptance_excess": excess,
        "step_squared": step2,
        "net_squared": net2,
        "path_after_upper": charged,
        "geometry_pass": geometry,
        "admitted_descent": geometry and s > 0 and excess > 0,
        "descriptive_zero_dual_gap_upper": dot(gradient, gradient) / 2,
        "optimality_gap_used_for_admission": False,
    }


def serialized(w, p, lam):
    # The literal supplied proposal is not generated by a production PG solver.
    current = tuple(float(x) for x in w)
    endpoint = tuple(x + float(lam) * float(y) for x, y in zip(current, p, strict=True))
    current_exact = tuple(F.from_float(x) for x in current)
    actual = tuple(F.from_float(x) - y for x, y in zip(endpoint, current_exact, strict=True))
    return current_exact, actual, {"stored_w": current, "stored_endpoint": endpoint, "lambda": lam}


def main():
    checks = []

    # Affine current drift is consistent with a nonzero current state.
    A, b, c = fixture()
    A[0], b[0], c[0] = scale(E1, -1), F(-1, 10), F(1, 10)
    _, g0, M = quantities(A, b, c, ZERO)
    p, w = (F(1, 290), F(0)), (F(1, 10), F(0))
    assert g0 == (F(-1, 240), F(0)) and M == F(29, 24)
    assert scale(g0, -1 / M) == p
    current, actual, encoding = serialized(w, p, F(1))
    interior = certificate(A, b, c, current, F(1, 5), actual)
    assert interior["admitted_descent"]
    assert interior["component_decreases"]["deficit"] > 0
    assert interior["component_decreases"]["drift"] < 0
    assert interior["component_decreases"]["proximal"] < 0
    checks.append(
        {"name": "interior_affine_drift_increases", **interior, "serialization": encoding}
    )

    # Two 3-4-5 circles and supplied projection multipliers1,1 determine y and b.
    p, z = (F(3, 100), F(1, 25)), (F(4, 25), F(3, 25))
    w, y = add(z, scale(p, -1)), add(scale(p, 2), z)
    a, rhs = (F(11, 5), F(2)), F(371, 250)
    A, b, c = fixture(a, rhs)
    _, g0, M = quantities(A, b, c, ZERO)
    assert M == F(371, 150) and scale(g0, -1 / M) == y
    assert dot(p, p) == STEP * STEP and dot(z, z) == NET * NET
    assert add(add(p, scale(y, -1)), add(p, z)) == ZERO
    current, full_r, full_encoding = serialized(w, p, F(1))
    full = certificate(A, b, c, current, F(1, 5), full_r)
    current, half_r, half_encoding = serialized(w, p, F(1, 2))
    half = certificate(A, b, c, current, F(1, 5), half_r)
    assert full["net_squared"] > NET * NET and not full["admitted_descent"]
    assert half["admitted_descent"] and half["net_squared"] < NET * NET
    checks.append(
        {
            "name": "both_active_then_declared_half_interpolation",
            "rational_projection": {
                "p": p,
                "w": w,
                "y": y,
                "step_multiplier": 1,
                "net_multiplier": 1,
            },
            "full": {**full, "serialization": full_encoding},
            "half": {**half, "serialization": half_encoding},
            "future_floating_projection_generator_tested": False,
        }
    )

    A, b, c = fixture()
    A[0] = scale(E1, -1)
    stationary = certificate(A, b, c, ZERO, F(0), ZERO)
    assert stationary["g0"] == ZERO and not stationary["admitted_descent"]
    assert stationary["J0"] > 0 and stationary["descriptive_zero_dual_gap_upper"] == 0
    checks.append({"name": "exact_stationary_positive_deficits", **stationary})

    # One rounding of the exact step hits the half-ULP of the even endpoint1/8.
    K = F(2**56)
    A, b, c = fixture((K, F(0)), F(1))
    exact_y = K / (K * K + 6)
    p, w = (F.from_float(float(exact_y)), F(0)), (F(1, 8), F(0))
    assert p[0] == F(1, 2**56)
    nominal = certificate(A, b, c, w, F(1, 5), p)
    current, actual, encoding = serialized(w, p, F(1))
    erased = certificate(A, b, c, current, F(1, 5), actual)
    assert nominal["admitted_descent"] and actual == ZERO
    assert erased["s"] == erased["gain"] == 0 and not erased["admitted_descent"]
    checks.append(
        {
            "name": "substantial_nominal_gain_erased_at_half_ulp",
            "exact_y": exact_y,
            "nominal_only": nominal,
            "actual": {**erased, "serialization": encoding},
            "separate_floating_gradient_M_division_tested": False,
        }
    )

    # Large global M from inactive orthogonal rows; no real gradients are used.
    A, b, c = fixture()
    K, T = F(512), F(512**2 + 7)
    A[3] = A[1] = scale(E2, K)
    _, g0, M = quantities(A, b, c, ZERO)
    p = (F(1) / (10 * T), F(0))
    assert M == T / 6 and scale(g0, -1 / M) == p
    large = certificate(A, b, c, ZERO, F(0), p)
    assert large["admitted_descent"]
    assert large["gain"] - large["s"] / 4 == (3 * T - 14) / (2400 * T * T)
    assert large["descriptive_zero_dual_gap_upper"] == K**4 / (7200 * T * T)
    assert large["descriptive_zero_dual_gap_upper"] > large["eta"]
    # A second fixed binary-scale fixture demonstrates that shrinkage is no cure
    # when even the full ray's convex first-order gain bound is below eta.
    K_floor, T_floor = F(4096), F(4096**2 + 7)
    A[3] = A[1] = scale(E2, K_floor)
    floor_case = certificate(A, b, c, ZERO, F(0), (F(1) / (10 * T_floor), F(0)))
    assert 0 < floor_case["s"] < floor_case["eta"] and not floor_case["admitted_descent"]
    checks.append(
        {
            "name": "large_M_descent_without_gap_gate",
            "progress": large,
            "floor_limited_ray": floor_case,
        }
    )

    w, tangent, inward = (NET, F(0)), (F(0), F(1, 100)), (F(-1, 100), F(0))
    assert dot(w, tangent) == 0 and dot(tangent, tangent) > 0
    assert 2 * dot(w, inward) + dot(inward, inward) < 0
    checks.append(
        {
            "name": "rational_net_boundary_geometry_logic",
            "w": w,
            "tangent": tangent,
            "inward": inward,
            "tangent_linear_coefficient": 2 * dot(w, tangent),
            "tangent_quadratic_coefficient": dot(tangent, tangent),
            "inward_full_scale_net_change": 2 * dot(w, inward) + dot(inward, inward),
            "tangent_is_not_a_feasible_exact_projection": True,
            "inward_geometry_does_not_certify_objective_gain": True,
        }
    )

    assert not any(
        name.split(".")[0] in {"torch", "transformers", "transformer_lens", "numpy", "scipy"}
        for name in sys.modules
    )
    return {
        "status": "SUPPLIED_DESCENT_DYADIC_WITNESSES_PASSED",
        "checks": checks,
        "arithmetic": "fractions.Fraction; binary64 endpoint operations only where stated",
        "dimension": 2,
        "rows": 12,
        "pairs_zero_based": PAIRS,
        "armijo_fraction": "1/4",
        "eta": "2^-30*max(1,J0)",
        "proposed_scale_indices": [0, 52],
        "production_algorithm_implemented": False,
        "optimizer_or_ray_search_executed": False,
        "native_fixture_read_or_run": False,
        "model_loads": 0,
        "real_forwards": 0,
        "real_derivatives": 0,
        "scientific_or_runtime_readiness_claim": False,
    }


if __name__ == "__main__":
    print(json.dumps(main(), default=str, sort_keys=True))
