"""Sparse nonnegative-cone analysis for secondary J-space comparisons.

J-space is represented here as the cone generated by nonnegative combinations
of J-Lens atoms.  It is not treated as an ordinary sign-symmetric linear
subspace: a direction and its negation are always fitted and reported
separately.
"""

from __future__ import annotations

import hashlib
import json
import math
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

DEFAULT_K_VALUES = (8, 16, 25)
DEFAULT_RANDOM_SEED = 20_260_824
JSPACE_ATOMS_MANIFEST_SCHEMA = "sp_lense.jspace_atoms_manifest.v1"
JSPACE_TOKEN_LABELS_SCHEMA = "sp_lense.jspace_token_labels.v1"
JSPACE_RECORD_SCHEMA = "sp_lense.jspace_record.v2"
JSPACE_REFERENCE_COMMIT = "581d398613e5602a5af361e1c34d3a92ea82ba8e"
JSPACE_PRIMARY_METHOD_IDS = ("gradient", "caa", "bipo", "persona_vector")
JSPACE_ALLOWED_STATUSES = (
    "complete",
    "not_run_resource_limited",
    "not_run_lens_layer_unavailable",
)
JSPACE_RESOURCE_LIMITS = {
    "max_working_gib": 8.0,
    "max_dictionary_read_tib": 4.0,
    "must_be_declared_before_loading_atom_tensor": True,
    "applied_identically_to_every_method_and_setup_for_a_model": True,
}
PINNED_JSPACE_LENSES: dict[str, dict[str, Any]] = {
    "Qwen/Qwen3.5-0.8B": {
        "repository": "neuronpedia/jacobian-lens",
        "filename": ("qwen3.5-0.8b/jlens/Salesforce-wikitext/Qwen3.5-0.8B_jacobian_lens.pt"),
        "revision": "6bb49967d3c51a12ccb5beac7146f6f5781f9d06",
        "file_sha256": "aa26b68ed73cf903280dbd8d1806f4ed8580aad205f396a5c997ee19259c9b48",
        "file_size_bytes": 48_242_373,
        "n_prompts": 233,
        "source_layers": list(range(23)),
        "fitted_model_id": "Qwen/Qwen3.5-0.8B",
        "fitted_model_revision": "not_reported_by_published_lens_artifact",
        "transfer_status": "same_named_checkpoint_lens_fit_revision_not_reported",
    },
    "Qwen/Qwen3.5-2B": {
        "repository": "neuronpedia/jacobian-lens",
        "filename": ("qwen3.5-2b-pt/jlens/Salesforce-wikitext/Qwen3.5-2B-Base_jacobian_lens.pt"),
        "revision": "0731326edff4ae730ffc5356fe1a4728c748b3a6",
        "file_sha256": "df64711d203b6c431a996a38f9e2b8b15124f4e277412cedaac95567ca52f818",
        "file_size_bytes": 192_945_948,
        "n_prompts": 335,
        "source_layers": list(range(23)),
        "fitted_model_id": "Qwen/Qwen3.5-2B-Base",
        "fitted_model_revision": "not_reported_by_published_lens_artifact",
        "transfer_status": "base_to_posttrained_checkpoint_exploratory_only",
    },
}


def _valid_sha256(value: Any) -> bool:
    return (
        isinstance(value, str)
        and len(value) == 64
        and all(character in "0123456789abcdef" for character in value)
    )


def _valid_git_commit(value: Any) -> bool:
    return (
        isinstance(value, str)
        and len(value) in {40, 64}
        and all(character in "0123456789abcdef" for character in value)
    )


def validate_locked_jspace_config(lock: Mapping[str, Any]) -> Mapping[str, Any]:
    """Fail closed unless the stage-1 lock contains the exact J-space preregistration."""

    evaluation = lock.get("evaluation")
    if not isinstance(evaluation, Mapping):
        raise TypeError("lock.evaluation must be an object")
    if evaluation.get("j_space_status") != "secondary_optional_non_gating":
        raise ValueError("lock.evaluation.j_space_status is not optional/non-gating")
    settings = evaluation.get("j_space")
    if not isinstance(settings, Mapping):
        raise TypeError("lock.evaluation.j_space must be an object")
    expected_keys = {
        "status",
        "required_for_primary_completion",
        "used_for_primary_ranking",
        "atoms_manifest_schema",
        "record_schema",
        "method_ids",
        "k_values",
        "random_control_count",
        "random_seed",
        "resource_limits",
        "allowed_statuses",
        "solver",
        "models",
    }
    if set(settings) != expected_keys:
        raise ValueError("lock.evaluation.j_space has unexpected or missing fields")
    expected_scalars = {
        "status": "secondary_optional_non_gating",
        "required_for_primary_completion": False,
        "used_for_primary_ranking": False,
        "atoms_manifest_schema": JSPACE_ATOMS_MANIFEST_SCHEMA,
        "record_schema": JSPACE_RECORD_SCHEMA,
        "method_ids": list(JSPACE_PRIMARY_METHOD_IDS),
        "k_values": list(DEFAULT_K_VALUES),
        "random_control_count": 50,
        "random_seed": DEFAULT_RANDOM_SEED,
        "resource_limits": JSPACE_RESOURCE_LIMITS,
        "allowed_statuses": list(JSPACE_ALLOWED_STATUSES),
    }
    mismatches = {
        field: (expected, settings.get(field))
        for field, expected in expected_scalars.items()
        if settings.get(field) != expected
    }
    if mismatches:
        raise ValueError(f"locked J-space configuration mismatch: {mismatches}")
    expected_solver = {
        "algorithm": (
            "deterministic_nonnegative_orthogonal_matching_pursuit_with_cyclic_nnls_refit"
        ),
        "dictionary_dtype": "float32",
        "selected_basis_nnls_dtype": "float64",
        "dictionary_normalized_once": True,
        "one_nested_pursuit_through_maximum_k_with_snapshots": True,
        "published_gradient_pursuit_equivalence_claim": False,
        "adaptation_reason": (
            "the_pinned_reference_repository_does_not_release_the_paper_"
            "gradient_pursuit_decomposition"
        ),
    }
    if settings.get("solver") != expected_solver:
        raise ValueError("locked J-space solver configuration differs from the implementation")

    source = lock.get("sources", {}).get("j_space")
    if not isinstance(source, Mapping) or source.get("commit") != JSPACE_REFERENCE_COMMIT:
        raise ValueError("locked J-space reference repository commit is invalid")
    models = settings.get("models")
    if not isinstance(models, Mapping) or set(models) != set(PINNED_JSPACE_LENSES):
        raise ValueError("locked J-space models differ from the two preregistered checkpoints")
    locked_model_ids = {
        str(item.get("model_id")) for item in lock.get("models", []) if isinstance(item, Mapping)
    }
    if locked_model_ids != set(PINNED_JSPACE_LENSES):
        raise ValueError("main model records and J-space model records differ")
    for model_id, expected_lens in PINNED_JSPACE_LENSES.items():
        model = models.get(model_id)
        if not isinstance(model, Mapping) or set(model) != {"lens"}:
            raise ValueError(f"locked J-space model record is invalid for {model_id}")
        if model.get("lens") != expected_lens:
            raise ValueError(f"locked J-space lens provenance differs for {model_id}")
    return settings


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _relative_artifact_path(manifest_path: Path, value: Any, *, field: str) -> Path:
    if not isinstance(value, str) or not value:
        raise ValueError(f"{field} must be a non-empty relative path")
    candidate = Path(value)
    if candidate.is_absolute() or ".." in candidate.parts:
        raise ValueError(f"{field} must stay within the manifest directory")
    resolved = (manifest_path.parent / candidate).resolve()
    try:
        resolved.relative_to(manifest_path.parent.resolve())
    except ValueError as error:  # pragma: no cover - guarded by the parts check above
        raise ValueError(f"{field} escapes the manifest directory") from error
    return resolved


def _torch() -> Any:
    try:
        import torch
    except ImportError as error:  # pragma: no cover - exercised only without research extras
        raise RuntimeError("J-space analysis requires the research extra (torch)") from error
    return torch


def _as_vector(value: Any, name: str) -> Any:
    torch = _torch()
    tensor = value.detach().to(device="cpu", dtype=torch.float64).contiguous()
    if tensor.ndim != 1 or tensor.numel() == 0:
        raise ValueError(f"{name} must be a non-empty one-dimensional tensor")
    if not bool(torch.isfinite(tensor).all().item()):
        raise ValueError(f"{name} must contain only finite values")
    return tensor


def _as_atoms(value: Any, width: int) -> Any:
    torch = _torch()
    # The published J-lens dictionary contains one row per vocabulary token.
    # Keeping the resident dictionary in float32 halves memory relative to the
    # old implementation. The small selected NNLS basis is promoted to float64.
    atoms = value.detach().to(device="cpu", dtype=torch.float32).contiguous()
    if atoms.ndim != 2 or atoms.shape[0] == 0 or atoms.shape[1] != width:
        raise ValueError(f"atoms must have shape [n_atoms, {width}]")
    if not bool(torch.isfinite(atoms).all().item()):
        raise ValueError("atoms must contain only finite values")
    norms = torch.linalg.vector_norm(atoms, dim=1)
    if bool((norms <= 0).any().item()):
        raise ValueError("J-space atoms must all have nonzero norm")
    return atoms


def tensor_float32_sha256(value: Any, *, row_chunk_size: int = 4096) -> str:
    """Hash shape plus canonical float32 bytes without a second full-size copy."""

    torch = _torch()
    tensor = value.detach().to(device="cpu")
    if not bool(torch.isfinite(tensor).all().item()):
        raise ValueError("cannot hash a tensor containing non-finite values")
    if row_chunk_size < 1:
        raise ValueError("row_chunk_size must be positive")
    header = json.dumps(
        {"shape": list(tensor.shape), "dtype": "float32"},
        sort_keys=True,
        separators=(",", ":"),
    ).encode("ascii")
    digest = hashlib.sha256(header + b"\n")
    if tensor.ndim == 0:
        chunks = (tensor.reshape(1),)
    elif tensor.ndim == 1:
        chunks = (tensor,)
    else:
        chunks = (
            tensor[start : start + row_chunk_size]
            for start in range(0, int(tensor.shape[0]), row_chunk_size)
        )
    for chunk in chunks:
        canonical = chunk.to(dtype=torch.float32).contiguous().numpy().astype("<f4", copy=False)
        digest.update(canonical.tobytes(order="C"))
    return digest.hexdigest()


@dataclass(frozen=True)
class PreparedAtomDictionary:
    """One validated, normalized J-lens dictionary reused by every target fit."""

    atoms: Any
    atom_norms: Any
    normalized_atoms: Any

    @property
    def n_atoms(self) -> int:
        return int(self.atoms.shape[0])

    @property
    def d_model(self) -> int:
        return int(self.atoms.shape[1])


def prepare_atom_dictionary(atoms: Any, *, width: int) -> PreparedAtomDictionary:
    torch = _torch()
    matrix = _as_atoms(atoms, width)
    atom_norms = torch.linalg.vector_norm(matrix, dim=1)
    normalized_atoms = (matrix / atom_norms[:, None]).contiguous()
    return PreparedAtomDictionary(
        atoms=matrix,
        atom_norms=atom_norms,
        normalized_atoms=normalized_atoms,
    )


@dataclass(frozen=True)
class ValidatedJSpaceManifest:
    path: Path
    manifest: dict[str, Any]
    manifest_sha256: str
    atoms_path: Path
    labels_path: Path
    token_labels: tuple[str, ...]


@dataclass(frozen=True)
class JSpaceAtomArtifact:
    metadata: ValidatedJSpaceManifest
    atoms: Any


def _load_json_object(path: Path, *, field: str) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise ValueError(f"{field} is not valid JSON: {error}") from error
    if not isinstance(value, dict):
        raise TypeError(f"{field} must contain one JSON object")
    return value


def _require_manifest_string(record: Mapping[str, Any], field: str) -> str:
    value = record.get(field)
    if not isinstance(value, str) or not value:
        raise ValueError(f"J-space manifest {field} must be a non-empty string")
    return value


def validate_jspace_atom_manifest(manifest_path: Path) -> ValidatedJSpaceManifest:
    """Validate provenance and file hashes without materializing the atom tensor."""

    path = manifest_path.resolve()
    if not path.is_file():
        raise FileNotFoundError(f"J-space atom manifest is missing: {path}")
    manifest = _load_json_object(path, field="J-space atom manifest")
    if manifest.get("schema_version") != JSPACE_ATOMS_MANIFEST_SCHEMA:
        raise ValueError("unsupported J-space atom manifest schema")
    if manifest.get("status") != "available":
        raise ValueError("J-space atom manifest is not marked available")
    for field in (
        "model",
        "lens",
        "construction",
        "atoms",
        "token_labels",
        "tokenizer",
        "unembedding",
    ):
        if not isinstance(manifest.get(field), Mapping):
            raise TypeError(f"J-space manifest {field} must be an object")

    model = manifest["model"]
    for field in ("id", "revision", "config_sha256"):
        _require_manifest_string(model, field)
    if not _valid_sha256(model["config_sha256"]):
        raise ValueError("J-space model config_sha256 is invalid")

    lens = manifest["lens"]
    for field in (
        "repository",
        "filename",
        "revision",
        "file_sha256",
        "fitted_model_id",
        "fitted_model_revision",
        "transfer_status",
    ):
        _require_manifest_string(lens, field)
    if not _valid_sha256(lens["file_sha256"]):
        raise ValueError("J-space lens file_sha256 is invalid")
    if (
        isinstance(lens.get("file_size_bytes"), bool)
        or not isinstance(lens.get("file_size_bytes"), int)
        or int(lens["file_size_bytes"]) < 1
    ):
        raise ValueError("J-space lens file_size_bytes must be a positive integer")
    if isinstance(lens.get("n_prompts"), bool) or not isinstance(lens.get("n_prompts"), int):
        raise TypeError("J-space lens n_prompts must be an integer")
    if int(lens["n_prompts"]) < 1:
        raise ValueError("J-space lens n_prompts must be positive")
    source_layers = lens.get("source_layers")
    if (
        not isinstance(source_layers, list)
        or not source_layers
        or any(
            isinstance(value, bool) or not isinstance(value, int) or value < 0
            for value in source_layers
        )
        or len(source_layers) != len(set(source_layers))
    ):
        raise ValueError("J-space lens source_layers must be unique non-negative integers")

    layer = manifest.get("layer")
    if isinstance(layer, bool) or not isinstance(layer, int) or layer < 0:
        raise ValueError("J-space manifest layer must be a non-negative integer")
    if layer not in source_layers:
        raise ValueError("J-space manifest layer is absent from the pinned lens source layers")
    construction = manifest["construction"]
    expected_construction = {
        "definition": "one_row_per_vocabulary_token_v_t_equals_J_layer_transpose_W_U_column_t",
        "matrix_orientation": "rows_equal_W_U_transpose_times_J_layer",
        "implementation": "transformer_lens.JacobianLens.lens_vectors",
        "cone": "sparse_nonnegative",
    }
    for field, expected in expected_construction.items():
        if construction.get(field) != expected:
            raise ValueError(f"unsupported J-space construction {field}")
    _require_manifest_string(construction, "implementation_package_version")
    reference_commit = _require_manifest_string(construction, "reference_repository_commit")
    if not _valid_git_commit(reference_commit):
        raise ValueError("J-space reference_repository_commit must be a lowercase Git hash")

    atoms_record = manifest["atoms"]
    atoms_path = _relative_artifact_path(path, atoms_record.get("path"), field="atoms.path")
    if not atoms_path.is_file():
        raise FileNotFoundError(f"J-space atom tensor is missing: {atoms_path}")
    for field in ("file_sha256", "float32_sha256"):
        if not _valid_sha256(atoms_record.get(field)):
            raise ValueError(f"J-space atoms {field} is invalid")
    if (
        atoms_record.get("format") != "torch_weights_only"
        or atoms_record.get("tensor_key") != "atoms"
    ):
        raise ValueError("J-space atoms must use the locked torch weights-only format")
    if atoms_record.get("dtype") != "float32":
        raise ValueError("J-space atoms must be stored as float32")
    shape = atoms_record.get("shape")
    if (
        not isinstance(shape, list)
        or len(shape) != 2
        or any(
            isinstance(value, bool) or not isinstance(value, int) or value < 1 for value in shape
        )
    ):
        raise ValueError("J-space atom shape must be [n_atoms, d_model]")
    if sha256_file(atoms_path) != atoms_record["file_sha256"]:
        raise ValueError("J-space atom tensor file hash mismatch")

    labels_record = manifest["token_labels"]
    labels_path = _relative_artifact_path(
        path, labels_record.get("path"), field="token_labels.path"
    )
    if not labels_path.is_file():
        raise FileNotFoundError(f"J-space token labels are missing: {labels_path}")
    if not _valid_sha256(labels_record.get("file_sha256")):
        raise ValueError("J-space token-label file_sha256 is invalid")
    if sha256_file(labels_path) != labels_record["file_sha256"]:
        raise ValueError("J-space token-label file hash mismatch")
    if labels_record.get("schema_version") != JSPACE_TOKEN_LABELS_SCHEMA:
        raise ValueError("J-space token-label manifest schema is invalid")
    if labels_record.get("token_ids") != "implicit_zero_to_n_minus_one":
        raise ValueError("J-space token IDs must be the complete ordered vocabulary")
    if labels_record.get("count") != shape[0]:
        raise ValueError("J-space token-label count differs from atom rows")
    labels_payload = _load_json_object(labels_path, field="J-space token labels")
    expected_label_keys = {
        "schema_version",
        "tokenizer_id",
        "tokenizer_revision",
        "token_ids",
        "tokens",
    }
    if set(labels_payload) != expected_label_keys:
        raise ValueError("J-space token-label file has unexpected fields")
    if (
        labels_payload["schema_version"] != JSPACE_TOKEN_LABELS_SCHEMA
        or labels_payload["token_ids"] != "implicit_zero_to_n_minus_one"
    ):
        raise ValueError("J-space token-label file identity is invalid")
    tokens = labels_payload["tokens"]
    if (
        not isinstance(tokens, list)
        or len(tokens) != shape[0]
        or any(not isinstance(token, str) for token in tokens)
    ):
        raise ValueError("J-space token-label file does not exactly cover atom rows")

    tokenizer = manifest["tokenizer"]
    for field in ("id", "revision"):
        _require_manifest_string(tokenizer, field)
    if tokenizer.get("vocab_size") != shape[0]:
        raise ValueError("J-space tokenizer vocabulary size differs from atom rows")
    if (
        labels_payload["tokenizer_id"] != tokenizer["id"]
        or labels_payload["tokenizer_revision"] != tokenizer["revision"]
    ):
        raise ValueError("J-space token labels use a different tokenizer identity")

    unembedding = manifest["unembedding"]
    if unembedding.get("shape") != [shape[1], shape[0]]:
        raise ValueError("J-space unembedding shape is inconsistent with atom shape")
    if not _valid_sha256(unembedding.get("float32_sha256")):
        raise ValueError("J-space unembedding float32_sha256 is invalid")

    return ValidatedJSpaceManifest(
        path=path,
        manifest=dict(manifest),
        manifest_sha256=sha256_file(path),
        atoms_path=atoms_path,
        labels_path=labels_path,
        token_labels=tuple(tokens),
    )


def load_jspace_atom_artifact(manifest_path: Path) -> JSpaceAtomArtifact:
    """Load an exact binary atom tensor after validating its provenance manifest."""

    torch = _torch()
    metadata = validate_jspace_atom_manifest(manifest_path)
    try:
        payload = torch.load(
            metadata.atoms_path,
            map_location="cpu",
            weights_only=True,
            mmap=True,
        )
    except TypeError:  # pragma: no cover - compatibility with older supported torch
        payload = torch.load(metadata.atoms_path, map_location="cpu", weights_only=True)
    if not isinstance(payload, dict) or set(payload) != {"atoms"}:
        raise ValueError("J-space atom tensor must contain exactly the 'atoms' tensor")
    atoms = payload["atoms"]
    expected_shape = tuple(metadata.manifest["atoms"]["shape"])
    if getattr(atoms, "dtype", None) != torch.float32 or tuple(atoms.shape) != expected_shape:
        raise ValueError("J-space atom tensor dtype/shape differs from its manifest")
    atoms = _as_atoms(atoms, expected_shape[1])
    observed_hash = tensor_float32_sha256(atoms)
    if observed_hash != metadata.manifest["atoms"]["float32_sha256"]:
        raise ValueError("J-space atom tensor content hash mismatch")
    return JSpaceAtomArtifact(metadata=metadata, atoms=atoms)


def estimate_jspace_resources(
    *, n_atoms: int, d_model: int, random_count: int, max_k: int
) -> dict[str, Any]:
    """Return conservative memory/traffic estimates before loading a giant dictionary."""

    for name, value in (
        ("n_atoms", n_atoms),
        ("d_model", d_model),
        ("random_count", random_count),
        ("max_k", max_k),
    ):
        if isinstance(value, bool) or not isinstance(value, int) or value < 1:
            raise ValueError(f"{name} must be a positive integer")
    atom_bytes = n_atoms * d_model * 4
    normalized_bytes = atom_bytes
    solver_bytes = n_atoms * 16 + d_model * 24 + max_k * d_model * 8
    peak_bytes = atom_bytes + normalized_bytes + solver_bytes
    matvec_count = (random_count + 2) * max_k
    dictionary_bytes_read_upper_bound = normalized_bytes * matvec_count
    gib = 1024**3
    return {
        "n_atoms": n_atoms,
        "d_model": d_model,
        "random_control_count": random_count,
        "maximum_sparsity": max_k,
        "dictionary_float32_gib": atom_bytes / gib,
        "normalized_dictionary_float32_gib": normalized_bytes / gib,
        "estimated_peak_working_gib": peak_bytes / gib,
        "dictionary_matvec_count": matvec_count,
        "dictionary_read_upper_bound_tib": dictionary_bytes_read_upper_bound / 1024**4,
        "estimate_is_conservative_and_excludes_python_model_loading": True,
    }


def extract_jspace_atoms(
    backend: Any, *, layer: int, chunk_size: int = 1024
) -> tuple[Any, tuple[str, ...], dict[str, Any]]:
    """Materialize all token-indexed J-lens vectors for one exact source layer."""

    torch = _torch()
    if backend.lens is None:
        raise RuntimeError("J-space atom extraction requires a loaded Jacobian lens")
    if isinstance(layer, bool) or not isinstance(layer, int) or layer < 0:
        raise ValueError("J-space extraction layer must be a non-negative integer")
    if layer not in set(map(int, backend.lens.source_layers)):
        raise ValueError(f"layer {layer} is absent from the configured Jacobian lens")
    if isinstance(chunk_size, bool) or not isinstance(chunk_size, int) or chunk_size < 1:
        raise ValueError("J-space atom chunk_size must be a positive integer")
    d_model = int(backend.model.cfg.d_model)
    unembedding = backend.model.W_U
    if unembedding.ndim != 2 or int(unembedding.shape[0]) != d_model:
        raise ValueError("model unembedding does not have shape [d_model, vocabulary]")
    n_atoms = int(unembedding.shape[1])
    atoms = torch.empty((n_atoms, d_model), dtype=torch.float32, device="cpu")
    with torch.inference_mode():
        for start in range(0, n_atoms, chunk_size):
            stop = min(n_atoms, start + chunk_size)
            token_ids = list(range(start, stop))
            vectors = backend.lens.lens_vectors(backend.model, token_ids, layer)
            if tuple(vectors.shape) != (stop - start, d_model):
                raise RuntimeError("Jacobian lens returned an unexpected atom chunk shape")
            atoms[start:stop].copy_(vectors.detach().to(device="cpu", dtype=torch.float32))
    raw_labels = backend.model.tokenizer.convert_ids_to_tokens(list(range(n_atoms)))
    if not isinstance(raw_labels, list) or len(raw_labels) != n_atoms:
        raise RuntimeError("tokenizer did not return one label per vocabulary token")
    labels = tuple(
        label if isinstance(label, str) else f"<unmapped_token_{token_id}>"
        for token_id, label in enumerate(raw_labels)
    )
    return (
        atoms,
        labels,
        {
            "n_atoms": n_atoms,
            "d_model": d_model,
            "unembedding_shape": [d_model, n_atoms],
            "unembedding_float32_sha256": tensor_float32_sha256(unembedding),
            "lens_n_prompts": int(backend.lens.n_prompts),
            "lens_source_layers": list(map(int, backend.lens.source_layers)),
        },
    )


def write_jspace_atom_artifact(
    *,
    manifest_path: Path,
    atoms_path: Path,
    labels_path: Path,
    atoms: Any,
    token_labels: Sequence[str],
    model_id: str,
    model_revision: str,
    model_config_sha256: str,
    lens_repository: str,
    lens_filename: str,
    lens_revision: str,
    lens_file_path: Path,
    lens_n_prompts: int,
    lens_source_layers: Sequence[int],
    lens_fitted_model_id: str,
    lens_fitted_model_revision: str,
    lens_transfer_status: str,
    layer: int,
    tokenizer_id: str,
    tokenizer_revision: str,
    unembedding_shape: Sequence[int],
    unembedding_float32_sha256: str,
    implementation_package_version: str,
    reference_repository_commit: str,
) -> ValidatedJSpaceManifest:
    """Write a binary dictionary plus a small provenance manifest and labels file."""

    torch = _torch()
    manifest_path = manifest_path.resolve()
    atoms_path = atoms_path.resolve()
    labels_path = labels_path.resolve()
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    for output_path, field in ((atoms_path, "atoms_path"), (labels_path, "labels_path")):
        try:
            output_path.relative_to(manifest_path.parent)
        except ValueError as error:
            raise ValueError(f"{field} must be inside the manifest directory") from error
    matrix = _as_atoms(atoms, int(atoms.shape[1]))
    labels = tuple(token_labels)
    if len(labels) != int(matrix.shape[0]) or any(not isinstance(label, str) for label in labels):
        raise ValueError("token_labels must contain exactly one string per atom")
    if not lens_file_path.resolve().is_file():
        raise FileNotFoundError(f"configured Jacobian lens file is missing: {lens_file_path}")
    if not _valid_sha256(model_config_sha256):
        raise ValueError("model_config_sha256 must be a lowercase SHA-256")
    if not _valid_sha256(unembedding_float32_sha256):
        raise ValueError("unembedding_float32_sha256 must be a lowercase SHA-256")
    if not _valid_git_commit(reference_repository_commit):
        raise ValueError("reference_repository_commit must be a lowercase Git hash")
    if list(unembedding_shape) != [int(matrix.shape[1]), int(matrix.shape[0])]:
        raise ValueError("unembedding_shape differs from the atom dictionary")
    locked_source_layers = list(lens_source_layers)
    if (
        not locked_source_layers
        or any(
            isinstance(value, bool) or not isinstance(value, int) or value < 0
            for value in locked_source_layers
        )
        or len(locked_source_layers) != len(set(locked_source_layers))
        or layer not in locked_source_layers
    ):
        raise ValueError("lens_source_layers must uniquely include the selected layer")

    torch.save({"atoms": matrix}, atoms_path)
    labels_record = {
        "schema_version": JSPACE_TOKEN_LABELS_SCHEMA,
        "tokenizer_id": tokenizer_id,
        "tokenizer_revision": tokenizer_revision,
        "token_ids": "implicit_zero_to_n_minus_one",
        "tokens": list(labels),
    }
    labels_path.write_text(
        json.dumps(labels_record, ensure_ascii=False, allow_nan=False, separators=(",", ":"))
        + "\n",
        encoding="utf-8",
    )
    manifest = {
        "schema_version": JSPACE_ATOMS_MANIFEST_SCHEMA,
        "status": "available",
        "model": {
            "id": model_id,
            "revision": model_revision,
            "config_sha256": model_config_sha256,
        },
        "lens": {
            "repository": lens_repository,
            "filename": lens_filename,
            "revision": lens_revision,
            "file_sha256": sha256_file(lens_file_path.resolve()),
            "file_size_bytes": lens_file_path.resolve().stat().st_size,
            "n_prompts": lens_n_prompts,
            "source_layers": locked_source_layers,
            "fitted_model_id": lens_fitted_model_id,
            "fitted_model_revision": lens_fitted_model_revision,
            "transfer_status": lens_transfer_status,
        },
        "layer": layer,
        "construction": {
            "definition": (
                "one_row_per_vocabulary_token_v_t_equals_J_layer_transpose_W_U_column_t"
            ),
            "matrix_orientation": "rows_equal_W_U_transpose_times_J_layer",
            "implementation": "transformer_lens.JacobianLens.lens_vectors",
            "implementation_package_version": implementation_package_version,
            "reference_repository_commit": reference_repository_commit,
            "cone": "sparse_nonnegative",
        },
        "atoms": {
            "path": atoms_path.relative_to(manifest_path.parent).as_posix(),
            "format": "torch_weights_only",
            "tensor_key": "atoms",
            "dtype": "float32",
            "shape": list(matrix.shape),
            "file_sha256": sha256_file(atoms_path),
            "float32_sha256": tensor_float32_sha256(matrix),
        },
        "token_labels": {
            "path": labels_path.relative_to(manifest_path.parent).as_posix(),
            "file_sha256": sha256_file(labels_path),
            "schema_version": JSPACE_TOKEN_LABELS_SCHEMA,
            "count": len(labels),
            "token_ids": "implicit_zero_to_n_minus_one",
        },
        "tokenizer": {
            "id": tokenizer_id,
            "revision": tokenizer_revision,
            "vocab_size": len(labels),
        },
        "unembedding": {
            "shape": list(unembedding_shape),
            "float32_sha256": unembedding_float32_sha256,
        },
    }
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    return validate_jspace_atom_manifest(manifest_path)


@dataclass(frozen=True)
class ConeFit:
    """A deterministic sparse nonnegative-cone reconstruction."""

    k_requested: int
    selected_indices: tuple[int, ...]
    active_indices: tuple[int, ...]
    coefficients: Any
    normalized_atom_coefficients: Any
    reconstruction: Any
    residual: Any
    target_norm: float
    reconstruction_norm: float
    residual_norm: float
    r2: float
    cosine: float
    coordinate_sweeps: int
    converged: bool

    def as_dict(self, *, top_n: int | None = None) -> dict[str, Any]:
        """Return a JSON-compatible summary without dense tensors."""

        torch = _torch()
        active = list(self.active_indices)
        ranked = sorted(
            active,
            key=lambda index: (-float(self.normalized_atom_coefficients[index]), index),
        )
        if top_n is not None:
            if top_n < 1:
                raise ValueError("top_n must be positive")
            ranked = ranked[:top_n]
        top = [
            {
                "index": index,
                "coefficient": float(self.coefficients[index].item()),
                "normalized_atom_coefficient": float(
                    self.normalized_atom_coefficients[index].item()
                ),
            }
            for index in ranked
        ]
        return {
            "k_requested": self.k_requested,
            "selected_count": len(self.selected_indices),
            "active_count": len(self.active_indices),
            "selected_indices": list(self.selected_indices),
            "top_indices": top,
            "target_norm": self.target_norm,
            "reconstruction_norm": self.reconstruction_norm,
            "residual_norm": self.residual_norm,
            "relative_residual_norm": self.residual_norm / self.target_norm,
            "reconstruction_r2": self.r2,
            "reconstruction_cosine": self.cosine,
            "coordinate_sweeps": self.coordinate_sweeps,
            "converged": self.converged,
            "all_coefficients_nonnegative": bool(
                (self.coefficients >= -torch.finfo(torch.float64).eps).all().item()
            ),
        }


def _coordinate_nnls(
    basis: Any,
    target: Any,
    *,
    initial: Any | None,
    max_sweeps: int,
    tolerance: float,
) -> tuple[Any, int, bool]:
    """Cyclic coordinate descent for a small, fixed NNLS support."""

    torch = _torch()
    width = basis.shape[1]
    coefficients = (
        torch.zeros(width, dtype=torch.float64)
        if initial is None
        else initial.detach().clone().to(dtype=torch.float64)
    )
    if coefficients.shape != (width,):
        raise ValueError("initial NNLS coefficients have the wrong shape")
    coefficients.clamp_(min=0)
    column_squared_norms = (basis * basis).sum(dim=0)
    if bool((column_squared_norms <= 0).any().item()):
        raise ValueError("NNLS basis contains a zero column")
    reconstruction = basis @ coefficients
    for sweep in range(1, max_sweeps + 1):
        previous = coefficients.clone()
        for coordinate in range(width):
            column = basis[:, coordinate]
            residual_without_coordinate = (
                target - reconstruction + column * coefficients[coordinate]
            )
            updated = torch.clamp(
                torch.dot(column, residual_without_coordinate) / column_squared_norms[coordinate],
                min=0,
            )
            reconstruction.add_(column * (updated - coefficients[coordinate]))
            coefficients[coordinate] = updated
        change = float(torch.linalg.vector_norm(coefficients - previous).item())
        scale = 1 + float(torch.linalg.vector_norm(coefficients).item())
        if change <= tolerance * scale:
            return coefficients, sweep, True
    return coefficients, max_sweeps, False


def nonnegative_sparse_cone_fit(
    target: Any,
    atoms: Any,
    *,
    k: int,
    max_coordinate_sweeps: int = 10_000,
    tolerance: float = 1e-10,
) -> ConeFit:
    """Fit at most ``k`` J-Lens atoms with deterministic nonnegative pursuit.

    Atoms are normalized for selection and conditioning, while the returned
    ``coefficients`` are converted back to the scale of the input atoms.
    Greedy ties resolve to the lowest atom index.
    """

    vector = _as_vector(target, "target")
    if isinstance(k, bool) or not isinstance(k, int) or k < 1:
        raise ValueError("k must be a positive integer")
    prepared = prepare_atom_dictionary(atoms, width=vector.numel())
    return sparse_cone_fits_prepared(
        vector,
        prepared,
        k_values=(k,),
        max_coordinate_sweeps=max_coordinate_sweeps,
        tolerance=tolerance,
    )[k]


def _cone_fit_from_state(
    *,
    vector: Any,
    prepared: PreparedAtomDictionary,
    k_requested: int,
    selected: Sequence[int],
    normalized_coefficients: Any,
    reconstruction: Any,
    target_norm: float,
    total_sweeps: int,
    all_converged: bool,
    tolerance: float,
) -> ConeFit:
    torch = _torch()
    coefficients = normalized_coefficients / prepared.atom_norms.to(dtype=torch.float64)
    residual = vector - reconstruction
    reconstruction_norm = float(torch.linalg.vector_norm(reconstruction).item())
    residual_norm = float(torch.linalg.vector_norm(residual).item())
    r2 = 1 - (residual_norm**2 / target_norm**2)
    cosine = (
        float(torch.dot(vector, reconstruction).item()) / (target_norm * reconstruction_norm)
        if reconstruction_norm > 0
        else 0.0
    )
    coefficient_threshold = tolerance * max(1.0, target_norm)
    active = tuple(
        index
        for index in selected
        if float(normalized_coefficients[index].item()) > coefficient_threshold
    )
    return ConeFit(
        k_requested=k_requested,
        selected_indices=tuple(selected),
        active_indices=active,
        coefficients=coefficients.clone(),
        normalized_atom_coefficients=normalized_coefficients.clone(),
        reconstruction=reconstruction.clone(),
        residual=residual,
        target_norm=target_norm,
        reconstruction_norm=reconstruction_norm,
        residual_norm=residual_norm,
        r2=r2,
        cosine=cosine,
        coordinate_sweeps=total_sweeps,
        converged=all_converged,
    )


def sparse_cone_fits_prepared(
    target: Any,
    prepared: PreparedAtomDictionary,
    *,
    k_values: tuple[int, ...] = DEFAULT_K_VALUES,
    max_coordinate_sweeps: int = 10_000,
    tolerance: float = 1e-10,
) -> dict[int, ConeFit]:
    """Run one nested pursuit and snapshot every requested sparsity."""

    torch = _torch()
    vector = _as_vector(target, "target")
    if vector.numel() != prepared.d_model:
        raise ValueError("target width differs from the prepared atom dictionary")
    ks = _validate_k_values(k_values)
    if max_coordinate_sweeps < 1:
        raise ValueError("max_coordinate_sweeps must be positive")
    if not math.isfinite(tolerance) or tolerance <= 0:
        raise ValueError("tolerance must be positive and finite")
    target_norm = float(torch.linalg.vector_norm(vector).item())
    if target_norm == 0:
        raise ValueError("target direction must have nonzero norm")

    selected: list[int] = []
    selected_mask = torch.zeros(prepared.n_atoms, dtype=torch.bool)
    normalized_coefficients = torch.zeros(prepared.n_atoms, dtype=torch.float64)
    reconstruction = torch.zeros_like(vector)
    total_sweeps = 0
    all_converged = True
    snapshots: dict[int, ConeFit] = {}
    requested = set(ks)
    maximum = min(max(ks), prepared.n_atoms)
    stopped = False

    for step in range(1, maximum + 1):
        residual = vector - reconstruction
        correlations = prepared.normalized_atoms @ residual.to(dtype=torch.float32)
        correlations[selected_mask] = -torch.inf
        best_index = int(torch.argmax(correlations).item())
        best_correlation = float(correlations[best_index].item())
        if best_correlation <= tolerance * target_norm:
            stopped = True
            break
        selected.append(best_index)
        selected_mask[best_index] = True
        index_tensor = torch.tensor(selected, dtype=torch.long)
        basis = prepared.normalized_atoms[index_tensor].T.to(dtype=torch.float64).contiguous()
        initial = normalized_coefficients[index_tensor].clone()
        fitted, sweeps, converged = _coordinate_nnls(
            basis,
            vector,
            initial=initial,
            max_sweeps=max_coordinate_sweeps,
            tolerance=tolerance,
        )
        total_sweeps += sweeps
        all_converged = all_converged and converged
        normalized_coefficients.zero_()
        normalized_coefficients[index_tensor] = fitted
        reconstruction = basis @ fitted
        if step in requested:
            snapshots[step] = _cone_fit_from_state(
                vector=vector,
                prepared=prepared,
                k_requested=step,
                selected=selected,
                normalized_coefficients=normalized_coefficients,
                reconstruction=reconstruction,
                target_norm=target_norm,
                total_sweeps=total_sweeps,
                all_converged=all_converged,
                tolerance=tolerance,
            )

    if stopped or max(ks) > maximum:
        for requested_k in ks:
            if requested_k not in snapshots:
                snapshots[requested_k] = _cone_fit_from_state(
                    vector=vector,
                    prepared=prepared,
                    k_requested=requested_k,
                    selected=selected,
                    normalized_coefficients=normalized_coefficients,
                    reconstruction=reconstruction,
                    target_norm=target_norm,
                    total_sweeps=total_sweeps,
                    all_converged=all_converged,
                    tolerance=tolerance,
                )
    missing = set(ks) - set(snapshots)
    if missing:  # pragma: no cover - defensive invariant
        raise RuntimeError(f"nested pursuit failed to snapshot sparsities: {sorted(missing)}")
    return {k_value: snapshots[k_value] for k_value in ks}


def _validate_k_values(k_values: tuple[int, ...] | list[int]) -> tuple[int, ...]:
    values = tuple(k_values)
    if not values or any(isinstance(k, bool) or not isinstance(k, int) or k < 1 for k in values):
        raise ValueError("k_values must contain positive integers")
    if len(values) != len(set(values)):
        raise ValueError("k_values must be unique")
    return values


def _percentile(value: float, reference: list[float]) -> float:
    if not reference:
        raise ValueError("percentile reference cannot be empty")
    less = sum(item < value for item in reference)
    equal = sum(item == value for item in reference)
    return 100 * (less + 0.5 * equal) / len(reference)


def _quantile(values: list[float], probability: float) -> float:
    ordered = sorted(values)
    index = max(0, math.ceil(probability * len(ordered)) - 1)
    return ordered[index]


def deterministic_random_directions(
    reference: Any, *, count: int, seed: int = DEFAULT_RANDOM_SEED
) -> Any:
    """Create seeded isotropic directions with the reference direction's norm."""

    torch = _torch()
    vector = _as_vector(reference, "reference")
    if isinstance(count, bool) or not isinstance(count, int) or count < 1:
        raise ValueError("random direction count must be positive")
    generator = torch.Generator(device="cpu")
    generator.manual_seed(seed)
    random_directions = torch.randn(
        (count, vector.numel()), dtype=torch.float64, generator=generator
    )
    norms = torch.linalg.vector_norm(random_directions, dim=1)
    target_norm = torch.linalg.vector_norm(vector)
    return random_directions / norms[:, None] * target_norm


def analyze_direction_against_jspace(
    direction: Any,
    atoms: Any,
    *,
    k_values: tuple[int, ...] = DEFAULT_K_VALUES,
    random_directions: Any | None = None,
    random_count: int = 50,
    random_seed: int = DEFAULT_RANDOM_SEED,
    max_coordinate_sweeps: int = 10_000,
    tolerance: float = 1e-10,
    token_labels: Sequence[str] | None = None,
    known_direction_float32_sha256: str | None = None,
    known_atoms_float32_sha256: str | None = None,
) -> dict[str, Any]:
    """Analyze ``v`` and ``-v`` against the cone and random-direction controls."""

    torch = _torch()
    vector = _as_vector(direction, "direction")
    prepared = (
        atoms
        if isinstance(atoms, PreparedAtomDictionary)
        else prepare_atom_dictionary(atoms, width=vector.numel())
    )
    if prepared.d_model != vector.numel():
        raise ValueError("direction width differs from the prepared atom dictionary")
    ks = _validate_k_values(k_values)
    labels = None if token_labels is None else tuple(token_labels)
    if labels is not None and (
        len(labels) != prepared.n_atoms or any(not isinstance(label, str) for label in labels)
    ):
        raise ValueError("token_labels must contain exactly one string per atom row")
    if known_direction_float32_sha256 is not None and not _valid_sha256(
        known_direction_float32_sha256
    ):
        raise ValueError("known_direction_float32_sha256 must be a lowercase SHA-256")
    if known_atoms_float32_sha256 is not None and not _valid_sha256(known_atoms_float32_sha256):
        raise ValueError("known_atoms_float32_sha256 must be a lowercase SHA-256")
    if random_directions is None:
        controls = deterministic_random_directions(vector, count=random_count, seed=random_seed)
    else:
        controls = random_directions.detach().to(device="cpu", dtype=torch.float64)
        if controls.ndim != 2 or controls.shape[1] != vector.numel() or controls.shape[0] == 0:
            raise ValueError("random_directions must have shape [n_random, d_model]")
        if not bool(torch.isfinite(controls).all().item()):
            raise ValueError("random_directions must be finite")
        if bool((torch.linalg.vector_norm(controls, dim=1) == 0).any().item()):
            raise ValueError("random_directions cannot contain zero vectors")

    random_by_k: dict[int, list[float]] = {k: [] for k in ks}
    random_cosine_by_k: dict[int, list[float]] = {k: [] for k in ks}
    for control in controls:
        control_fits = sparse_cone_fits_prepared(
            control,
            prepared,
            k_values=ks,
            max_coordinate_sweeps=max_coordinate_sweeps,
            tolerance=tolerance,
        )
        for k, fit in control_fits.items():
            random_by_k[k].append(fit.r2)
            random_cosine_by_k[k].append(fit.cosine)

    signs: dict[str, Any] = {}
    for sign_name, target in (("positive", vector), ("negative", -vector)):
        fits: dict[str, Any] = {}
        sign_fits = sparse_cone_fits_prepared(
            target,
            prepared,
            k_values=ks,
            max_coordinate_sweeps=max_coordinate_sweeps,
            tolerance=tolerance,
        )
        for k, fit in sign_fits.items():
            summary = fit.as_dict(top_n=k)
            if labels is not None:
                summary["top_indices"] = [
                    {**item, "token_label": labels[int(item["index"])]}
                    for item in summary["top_indices"]
                ]
            summary.update(
                {
                    "random_r2_percentile": _percentile(fit.r2, random_by_k[k]),
                    "random_cosine_percentile": _percentile(fit.cosine, random_cosine_by_k[k]),
                    "random_r2_mean": sum(random_by_k[k]) / len(random_by_k[k]),
                    "random_r2_p95": _quantile(random_by_k[k], 0.95),
                    "random_cosine_mean": sum(random_cosine_by_k[k]) / len(random_cosine_by_k[k]),
                    "random_cosine_p95": _quantile(random_cosine_by_k[k], 0.95),
                }
            )
            fits[str(k)] = summary
        signs[sign_name] = fits
    return {
        "analysis_type": "sparse_nonnegative_cone",
        "direction_float32_sha256": (
            known_direction_float32_sha256
            if known_direction_float32_sha256 is not None
            else tensor_float32_sha256(vector)
        ),
        "atoms_float32_sha256": (
            known_atoms_float32_sha256
            if known_atoms_float32_sha256 is not None
            else tensor_float32_sha256(prepared.atoms)
        ),
        "n_atoms": prepared.n_atoms,
        "d_model": prepared.d_model,
        "k_values": list(ks),
        "random_control_count": int(controls.shape[0]),
        "random_seed": random_seed if random_directions is None else None,
        "random_directions_float32_sha256": tensor_float32_sha256(controls),
        "solver": {
            "algorithm": "deterministic_nonnegative_orthogonal_matching_pursuit_with_cyclic_nnls_refit",
            "paper_method_adaptation": (
                "The paper specifies gradient pursuit but its pinned reference repository "
                "does not release that decomposition. This deterministic nonnegative "
                "pursuit is an explicitly labelled approximation, not byte-equivalent code."
            ),
            "dictionary_dtype": "float32",
            "selected_basis_nnls_dtype": "float64",
            "dictionary_normalized_once": True,
            "one_nested_pursuit_snapshotted_at_each_k": True,
            "max_coordinate_sweeps": max_coordinate_sweeps,
            "tolerance": tolerance,
        },
        "selected_indices_have_token_labels": labels is not None,
        "signs": signs,
        "claim_boundary": (
            "cone overlap is secondary evidence and is neither necessary nor sufficient "
            "for successful behavioral steering"
        ),
    }


def split_cone_components(target: Any, fit: ConeFit) -> dict[str, Any]:
    """Split a direction into its fitted cone approximation and exact residual."""

    torch = _torch()
    vector = _as_vector(target, "target")
    cone = fit.reconstruction.detach().to(device="cpu", dtype=torch.float64)
    if cone.shape != vector.shape:
        raise ValueError("cone fit and target have different shapes")
    residual = vector - cone
    target_norm = float(torch.linalg.vector_norm(vector).item())
    cone_norm = float(torch.linalg.vector_norm(cone).item())
    residual_norm = float(torch.linalg.vector_norm(residual).item())
    exact_error = float(torch.linalg.vector_norm(vector - cone - residual).item())
    return {
        "cone_component": cone,
        "residual_component": residual,
        "target_norm": target_norm,
        "cone_component_norm": cone_norm,
        "residual_component_norm": residual_norm,
        "cone_norm_fraction": cone_norm / target_norm,
        "residual_norm_fraction": residual_norm / target_norm,
        "reconstruction_r2": 1 - (residual_norm**2 / target_norm**2),
        "exact_additive_reconstruction_error": exact_error,
        "components_are_not_assumed_orthogonal": True,
    }


def norm_match_component(component: Any, reference: Any) -> Any:
    """Scale a nonzero component to the reference norm for intervention ablations."""

    torch = _torch()
    vector = _as_vector(component, "component")
    target = _as_vector(reference, "reference")
    if vector.shape != target.shape:
        raise ValueError("component and reference must have the same shape")
    component_norm = torch.linalg.vector_norm(vector)
    if float(component_norm.item()) == 0:
        raise ValueError("cannot norm-match a zero component")
    return vector * (torch.linalg.vector_norm(target) / component_norm)


def fit_and_split_direction(
    direction: Any,
    atoms: Any,
    *,
    k: int,
    max_coordinate_sweeps: int = 10_000,
    tolerance: float = 1e-10,
) -> dict[str, Any]:
    """Fit a cone approximation and return raw and norm-matched components."""

    fit = nonnegative_sparse_cone_fit(
        direction,
        atoms,
        k=k,
        max_coordinate_sweeps=max_coordinate_sweeps,
        tolerance=tolerance,
    )
    split = split_cone_components(direction, fit)
    split["fit"] = fit
    split["fit_summary"] = fit.as_dict(top_n=k)
    split["norm_matched_cone_component"] = (
        norm_match_component(split["cone_component"], direction)
        if split["cone_component_norm"] > 0
        else None
    )
    split["norm_matched_residual_component"] = (
        norm_match_component(split["residual_component"], direction)
        if split["residual_component_norm"] > 0
        else None
    )
    return split
